return PlaceObj('ModDef', {
	'title', "Elevator A.I.",
	'description', "Elevator A.I.\r\nv2.2 - Sept 27th, 2018\r\nby SKiRich",
	'image', "Images/ElevatorAILogo.png",
	'last_changes', "v2.2 Sept 27th, 2018\r\n- Minor bug fix around notifications",
	'id', "PuW72FR",
	'steam_id', "1504430797",
	'author', "SkiRich",
	'version', 19,
	'lua_revision', 235636,
	'code', {"Code/EAI_1Init.lua","Code/EAI_2Panels.lua"},
	'loctables', {{filename = "Locale/FR-fr.csv",language = "French"},{filename = "Locale/PL-pl.csv",language = "Polish"},{filename = "Locale/DE-de.csv",language = "German"},{filename = "Locale/BG-bg.csv",language = "Bulgarian"},{filename = "Locale/ES-es.csv",language = "Spanish"},{filename = "Locale/RU-ru.csv",language = "Russian"}},
	'saved', 1538357954,
	'screenshot1', "Images/ElevatorAILogo.png",
	'screenshot2', "Images/EAIdisabled.png",
	'screenshot3', "Images/EAIip1.png",
	'screenshot4', "Images/EAInotInstalled.png",
	'screenshot5', "Images/EAIschedule.png",
	'TagGameplay', true,
	'TagTools', true,
	'TagOther', true,
})