return PlaceObj('ModDef', {
	'title', "Elevator A.I.",
	'description', "Elevator A.I.\nv2.2.2\nby SKiRich",
	'image', "ElevatorAILogo.png",
	'last_changes', "v2.2.2 Dec 15th, 2018",
	'ignore_files', {
		"*.git/*",
		"*.svn/*",
		"*.gitignore",
		"*Images/*",
	},
	'id', "PuW72FR",
	'steam_id', "1504430797",
	'pops_desktop_uuid', "61f8d83b-4ba6-411d-be5a-792fe6d95b77",
	'pops_any_uuid', "06f67c2e-9c98-4985-8a05-67558e42296e",
	'author', "SkiRich",
	'version', 27,
	'lua_revision', 233360,
	'saved_with_revision', 240674,
	'code', {"Code/EAI_1Init.lua","Code/EAI_2Panels.lua"},
	'loctables', {{filename = "Locale/FR-fr.csv",language = "French"},{filename = "Locale/PL-pl.csv",language = "Polish"},{filename = "Locale/DE-de.csv",language = "German"},{filename = "Locale/BG-bg.csv",language = "Bulgarian"},{filename = "Locale/ES-es.csv",language = "Spanish"},{filename = "Locale/RU-ru.csv",language = "Russian"}},
	'saved', 1548451146,
	'screenshot1', "Images/ElevatorAILogo.png",
	'screenshot2', "Images/EAIdisabled.png",
	'screenshot3', "Images/EAIip1.png",
	'screenshot4', "Images/EAInotInstalled.png",
	'screenshot5', "Images/EAIschedule.png",
	'TagGameplay', true,
	'TagTools', true,
	'TagOther', true,
})